# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy the HTML and CSS files into the Nginx default public directory
COPY index.html /usr/share/nginx/html/
COPY main.css /usr/share/nginx/html/
COPY logo-orange-blockchainblockchain /usr/share/nginx/html/